# Site settings
name: Antimatter
title: Anti's Blog
description: "A piece of the universe looking spectively, trying to generate another universe within the host one."
baseurl: ""
url: "https://antimatter543.github.io"
github_username: antimatter543
# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title 
# pretty # https://jekyllrb.com/docs/permalinks/ is equiv. to permalink: /:categories/:year/:month/:day/:title